#!/bin/bash

## sarplot.sh
## Hereward Cooper - 14/10/2009
## A hack to plot various system resource information from sar using gnuplot

## Start off doing some checks for required programs
if [ ! -f /usr/bin/gnuplot ]
then
        echo "CRITICAL: gnuplot missing!"
        exit 1;
fi

if [ ! -f /usr/bin/sadf ]
then
        echo "CRITICAL: sar missing!"
        exit 1;
fi


#####################################################
## Next Define some of the graphs you want to plot ##
## metric = the flag to pass sar                   ##
## field = the coloumn in the output to plot       ##
## title = human readable version of the field     ##
#####################################################

# Swap Usage
if [[ $1 == "swap" ]]
then
        sar -r | grep swpused || echo "No Swap Detected"; exit 1
        metric="-r"
        field="kbbuffers"
        title="% Swap Usage"

# 1 Minute Load Average
elif [[ $1 == "load" ]]
then
        metric="-q"
        field="ldavg-1"
        title="1 Minute Load Average"

# Disk Read IO
elif [[ $1 == "io" ]]
then
        metric="-b"
        field="rtps"
        title="Read Requests per Second"

# Disk Write IO
elif [[ $1 == "iow" ]]
then
        metric="-b"
        field="wtps"
        title="Write Requests per Second"

# Network Inbound
elif [[ $1 == "netin" ]]
then
        metric="-n DEV "
        field="eth0.*rxbyt"
        title="kB/s Recieved on eth0"

elif [[ $1 == "ctx" ]]
then
        metric="-w"
        field="cswch"
        title="Context switches/second"

# Failback to CPU %idle if nothing defined
elif [[ $1 == "cpu" || $# -eq 0 ]]
then
        metric="-u"
        field="%idle"
        title="CPU %Idle"
else
        echo "Invalid metric specified!"
        exit 1
fi

#####################################
## This is where the magic happens ##
#####################################

TMPFILE=`mktemp /tmp/sarplot.XXXXXXXXXX`

/usr/bin/sadf -- $metric | awk "/$field/ {print \$3,\$6}" > $TMPFILE

echo "set terminal png;
set title '$title';
set xdata time;
set timefmt '%s';
set xlabel 'Time';
plot '$TMPFILE' using 1:2 with lines title '$title';" | gnuplot
rm -f $TMPFILE
